# Generated by Django 5.1.3 on 2024-11-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('TD', 'Tandoori'), ('CG', 'Chicken Gravy'), ('FR', 'Fried Rice'), ('ST', 'Starters'), ('MC', 'Mutton Gravy'), ('DB', 'Dum Biryani')], max_length=2)),
                ('product_images', models.ImageField(upload_to='product')),
            ],
        ),
    ]
